// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQE93srcOKxbBLxAH1HWT-rdvKKaMRlxw',
    appId: '1:23043592277:web:06c3fd8b4c1fe42eba44dc',
    messagingSenderId: '23043592277',
    projectId: 'sizzle-a888e',
    authDomain: 'sizzle-a888e.firebaseapp.com',
    storageBucket: 'sizzle-a888e.firebasestorage.app',
    measurementId: 'G-J93P1GTES6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiPkdb_-878tlF6ZxEZqDDUl5I0qLv3tA',
    appId: '1:23043592277:android:eb5ab04db99014e6ba44dc',
    messagingSenderId: '23043592277',
    projectId: 'sizzle-a888e',
    storageBucket: 'sizzle-a888e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBd4WeFACGdnz4al4iblBPzoODs_CfXng4',
    appId: '1:23043592277:ios:ce28d3d92049df46ba44dc',
    messagingSenderId: '23043592277',
    projectId: 'sizzle-a888e',
    storageBucket: 'sizzle-a888e.firebasestorage.app',
    iosClientId: '23043592277-b7ro6k579clu9ri9hlgh51dncanvd9p1.apps.googleusercontent.com',
    iosBundleId: 'com.example.sizzle',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBd4WeFACGdnz4al4iblBPzoODs_CfXng4',
    appId: '1:23043592277:ios:ce28d3d92049df46ba44dc',
    messagingSenderId: '23043592277',
    projectId: 'sizzle-a888e',
    storageBucket: 'sizzle-a888e.firebasestorage.app',
    iosClientId: '23043592277-b7ro6k579clu9ri9hlgh51dncanvd9p1.apps.googleusercontent.com',
    iosBundleId: 'com.example.sizzle',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQE93srcOKxbBLxAH1HWT-rdvKKaMRlxw',
    appId: '1:23043592277:web:722345a253702162ba44dc',
    messagingSenderId: '23043592277',
    projectId: 'sizzle-a888e',
    authDomain: 'sizzle-a888e.firebaseapp.com',
    storageBucket: 'sizzle-a888e.firebasestorage.app',
    measurementId: 'G-24YRJ1CV2B',
  );
}
